language: node_js
node_js:
  - 14

services:
  - docker

before_install:
  - docker build -t gioshara/dockerized-vite-app -f Dockerfile.dev .

script:
  - docker run -e CI=true gioshara/dockerized-vite-app npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  region: "eu-central-1"
  app: "dockerized-vite-app"
  env: "Dockerizedviteapp-env"
  bucket_name: "elasticbeanstalk-eu-central-1-311534292817"
